### ISSUE TITLE
Tag new version v0.15.3

### ISSUE THREAD

**Issue by rjhilgefort** [logankoester/grunt-phonegap#135]
I'm currently maintaining a fork just so I can more frequently version this codebase. There hasn't been a tag/release in over a year and a half. I realize this is somewhat of a dead/dying project, but tagging every so often (after big pull requests, features, etc...) would be a big help for using this as a dependency.

**Comment by AO16** [comment]
:+1:

**Comment by gabrielpoca** [comment]
Hei @rjhilgefort , you're right, and as a contributor to this project I apologize. I've bumped a new version and I'll be looking into the issues and see what I can do.

**Comment by rjhilgefort** [comment]
:+1: Thanks!

**Comment by rjhilgefort** [comment]
:+1: :+1:
