### ISSUE TITLE
Build hangs while "Cloning root directory"

### ISSUE THREAD

**Issue by julmot** [logankoester/grunt-phonegap#137]
After running `$ grunt phonegap:build` everything seems to be ok, but unfortunately the build hangs at a certain step:

![done](https://cloud.githubusercontent.com/assets/8310677/12138814/0ab84708-b45c-11e5-844e-d0d101c98d63.png)

My grunt task:
```javascript
phonegap: {
	config: {
		root: 'dist/web-v0.4.1/',
		config: 'phonegap/config.xml',
		cordova: 'phonegap/.cordova',
		path: 'phonegap-build/',
		platforms: ['android']
	}
}
```
What can be the reason? How to debug this issue?

**Comment by AdrianoMoura** [comment]
I had the same issue too. Someone figured out how to solve this?

**Comment by julmot** [comment]
@AdrianoMoura Unfortunately no. As you can see in the [overview](https://github.com/logankoester/grunt-phonegap/issues/created_by/julmot) I have opened a few more issues. I didn't get the build to work. So I switched to the native phonegap cli. 
But I noticed that it has something todo with my test project. I tested it with another (empty) project with just an `index.html` inside and the build worked (until another error, see above). But what exactly it is, is unknown to me.

**Comment by kamiljano** [comment]
same problem here. I was really hoping to switch to grunt build so that I could get rid of third party libraries from my repo, take sass into use and write a few jasmine tests that could easily be executed from the command line, but the build never finishes preventing me from doing the switch over... what is that repository cloning anyway? I don't want the plugin to clone any repos...

**Comment by julmot** [comment]
@kamiljano I think you've misunderstand "Cloning root directory". It will clone your application into the phonegap build folder, not clone any remote repository.

**Comment by kamiljano** [comment]
@julmot either way, it doesn't finish the build process.

**Comment by grdonda** [comment]
try to change the clone_root.js file by adding the line ncp.limit = 512; below the call of NCP module. 

ncp = require ('ncp').ncp;
ncp.limit = 512;

work like a charm.

**Comment by grdonda** [comment]
http://pastebin.com/u6pbmgZA

**Comment by AdrianoMoura** [comment]
Thanks @grdonda works to me!!!

**Comment by julmot** [comment]
@grdonda If this solves the issue, would you please be so kind and do a PR?

**Comment by grdonda** [comment]
the solution already exists in the NCP module, the grunt-phonegap module has not been updated. the grunt-phonegap module (https://www.npmjs.com/package/grunt-phonegap) is with the outdated dependencies. look at the above address. that way, when installing I updated the internal modules within the grunt-phonegap module. (https://travis-ci.org/AvianFlu/ncp/pull_requests)

**Comment by julmot** [comment]
well, then could you do a PR with updating the related dependencies?

**Comment by grdonda** [comment]
I will send the PR to grunt-phonegap perform update of internal dependencies related to this issue. tks

**Comment by julmot** [comment]
thx, please refer the PR in this issue after that.

**Comment by grdonda** [comment]
I will not get this moment. Would you help me ? or notify them?

**Comment by julmot** [comment]
I didn't understand you. Help you with what?

**Comment by grdonda** [comment]
I am currently unable to send the PR now.

2016-01-18 13:38 GMT-03:00 Julian <notifications@github.com>:

**Comment by julmot** [comment]
@grdonda No problem, it has time... The PR from September 2015 are still not merged...

**Comment by grdonda** [comment]
ok. tks.

2016-01-18 17:07 GMT-03:00 Julian <notifications@github.com>:

**Comment by mourice** [comment]
Build still hang when I use
"npm install grunt-phonegap --save-dev
Checked the npm module for grunt phonegap and found that
ncp.limit = 512 is not present inside root file
