### ISSUE TITLE
FirefoxOS support

### ISSUE THREAD

**Issue by CitizenOfRome** [logankoester/grunt-phonegap#91]
Running `grunt phonegap:build` with [`firefoxos`](http://docs.phonegap.com/en/3.4.0/guide_platforms_firefoxos_index.md.html) as one of the platforms throws up the following warning:

```
Skipping platform 'firefoxos' (SDK not compatible)
```

**Comment by julmot** [comment]
As Firefox OS is not getting maintained anymore, it seems that H5OS should be supported and Firefox OS dropped.
